// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJpKBSW8Fum7NRK-2crUm002vZWRys-Wc',
    appId: '1:1070568438993:web:4f52b347788c1e6d2959f0',
    messagingSenderId: '1070568438993',
    projectId: 'eventmanagementapplicati-92181',
    authDomain: 'eventmanagementapplicati-92181.firebaseapp.com',
    storageBucket: 'eventmanagementapplicati-92181.firebasestorage.app',
    measurementId: 'G-WJYPF9S5E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4xCOzslm6XVjJYyAEwIcRBap2me2g1w',
    appId: '1:1070568438993:android:c10e6e79713afae62959f0',
    messagingSenderId: '1070568438993',
    projectId: 'eventmanagementapplicati-92181',
    storageBucket: 'eventmanagementapplicati-92181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8PYR5miUpXmulW6KpC62v2uD69YkHPY',
    appId: '1:1070568438993:ios:2a9bcdc5f056011f2959f0',
    messagingSenderId: '1070568438993',
    projectId: 'eventmanagementapplicati-92181',
    storageBucket: 'eventmanagementapplicati-92181.firebasestorage.app',
    iosBundleId: 'com.example.eventmanagementapp',
  );
}
